#!/usr/bin/awk -f

BEGIN {
	FS = "\t"
	RS = "\n"
	if (split(mark, amark, ",") == 2) {
		markfield = amark[1]
		marktext  = amark[2]
	}
}

NR == 1 {
	printf("<table class=\"listing\">\n<tr>\t<th>")
	gsub("\t", "</th>\t<th>")
	printf($0 "</th>\t</tr>\n")
	next
}

{
	if (NR % 2)
		class = "even"
	else
		class = "odd"

	if ($NF == "TOTAL")
		class = class " bold-black"

	if (markfield && $markfield == marktext)
		class = class " bold-red"

	gsub("\t", "</td>\t<td>")
	printf("<tr class=\"" class "\">\t<td>" $0 "</td>\t</tr>\n")
}

END {
	if (NR) printf("</table>\n")
}
