#!/usr/bin/awk -f

BEGIN {
	FS = "\t"
	RS = "\n"
}

NR == 1 {
	printf("<table class=\"listing\">\n<tr>\t<th>")
	gsub("\t", "</th>\t<th>")
	printf($0 "</th>\t</tr>\n")
	next
}

{
	if (NR % 2)
		class = "even"
	else
		class = "odd"

	gsub("\t", "</td>\t<td>")
	printf("<tr class=\"" class "\">\t<td>" $0 "</td>\t</tr>\n")
}

END {
	if (NR) printf("</table>\n")
}
