#!/usr/bin/awk -f

BEGIN {
	FS = "\t"
	RS = "\n"
}

NR == 1 {
	printf("<table border=1>\n<tr>\t<th>")
	gsub("\t", "</th>\t<th>")
	printf($0 "</th>\t</tr>\n")
	next
}

{
	gsub("\t", "</td>\t<td>")
	printf("<tr>\t<td>" $0 "</td>\t</tr>\n")
}

END {
	if (NR) printf("</table>\n")
}
