#!/bin/bash -ue
#
# league_scoreboard - Generate a scoreboard of a ConquerClub Clan League
#
#    Copyright (C) 2016 Rodrigo Silva (MestreLion) <conquerclub@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>

# Reference:
# http://www.conquerclub.com/public.php?mode=showclans3&search_status=&search_clanleague=44


url=http://www.conquerclub.com/public.php?mode=showclans3  # Clan Leagues

ongoing=${1:-0}  # Include ongoing games?
league=${2:-44}  # Clan League 7 - Second Division

printf "RANK\tCLAN\tMATCHES\tM.WON\tM.DRAW\tM.LOST\tPOINTS\tG.DIFF\tGAMES\n"

wget -qO- --post-data "search_clanleague=${league}&search_status=" "$url" |
awk -v q="'" -v ongoing="$ongoing" '
	BEGIN {
		FS  = "([ \t]*(</nobr>)?</td><td>(<nobr>)?[ \t]*)|</td>"
		OFS = "\t"
		RS  = "<tr class=" q "(even|odd)" q "><td>"
		split("Matches,MW,MD,ML,GW,GL", cols, ",")
	}

	NR == 1 {
		next
	}

	# $1 = (Battle) Id, numeric
	# $2 = (Battle) Name, "CL7 Second Division - Rd 5 - KNT vs SOH"
	# $3 = Clans, "PACK VS SoH", with clans URL
	#	"<a href="q"/public.php?mode=showclans1&ClanId=88"q">PACK </a> VS <a"
	# $4 = Dates, "2015-12-15 - 2015-12-17", "-", "- 2013-10-10"
	# $5 = Status
	# 	"War Waiting/ Games None"
	# 	"War Active/ Games Active"
	# 	"War Active/ Games Inactive"
	# 	"War Complete/ Games Inactive"
	# $6 = Score, "PACK  4  VS SoH  2"
	# $7 = Winners, "", "Otpisani", "the Fallen, The Pig Renters"
	# $8 = Details URL, "/public.php?mode=showclanwar&ClanWarId=12"

	{
		split($6, score, / +(VS)? */)
		clanA = score[1]
		winsA = score[2]
		clanB = score[3]
		winsB = score[4]

		if (! (clanA in clans)) {
			clans[clanA] = clanA
			for (col in cols)
				data[clanA, cols[col]] = 0
		}
		if (! (clanB in clans)) {
			clans[clanB] = clanB
			for (col in cols)
				data[clanB, cols[col]] = 0
		}

		if (ongoing)
			criteria = ($5 != "War Waiting/ Games None")
		else
			criteria = ($5 == "War Active/ Games Inactive")

		if (criteria) {
			data[clanA, "Matches"] += 1
			data[clanB, "Matches"] += 1

			if (winsA > winsB) {
				data[clanA, "MW"] += 1
				data[clanB, "ML"] += 1
			}
			else if (winsA < winsB) {
				data[clanA, "ML"] += 1
				data[clanB, "MW"] += 1
			}
			else {
				data[clanA, "MD"] += 1
				data[clanB, "MD"] += 1
			}
		}

		data[clanA, "GW"] += winsA
		data[clanA, "GL"] += winsB
		data[clanB, "GW"] += winsB
		data[clanB, "GL"] += winsA
	}

	END {
		for (clan in clans) {
			print \
				clan,
				data[clan, "Matches"],
				data[clan, "MW"],
				data[clan, "MD"],
				data[clan, "ML"],
				2 * data[clan, "MW"] + 1 * data[clan, "MD"],
				data[clan, "GW"] - data[clan, "GL"],
				data[clan, "GW"] "-" data[clan, "GL"]
		}
	}' |
sort --key=6nr,8nr |
IFS=$'\t' grep -n '' |
tr ":" "\t"
