#!/bin/bash -ue
#
# Apache configuration generator
# Copyright (C) 2016 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>

project=conquerclub

# Constants and other globals - DO NOT CHANGE! --------------------------------

myname=${0##*/}
mydir=$(dirname "$(readlink -f "$0")")

docroot=$mydir/www
cgibin=$mydir/cgi-bin

target=/etc/apache2/sites-available/$project

# Do stuff -------------------------------------------------------------------

sudo rm -f -- "$target"

{
cat <<EOF
# Created by $mydir/$myname

ScriptAlias /$project/cgi-bin/ "$cgibin/"
Alias /$project "$docroot"
<Directory "$docroot">
	Options +Indexes
	IndexOptions FancyIndexing
	DirectoryIndex index.php index.html

	<IfModule mod_php5.c>
		php_flag   display_startup_errors  on
		php_flag   display_errors          on
		php_flag   html_errors             on
		php_flag   track_errors            on
		php_flag   log_errors              on
		php_value  error_reporting         -1
		php_value  log_errors_max_len      0

		# Already the default:
#		php_flag   log_errors              on
#		php_flag   report_memleaks         on
#		php_flag   ignore_repeated_errors  off
#		php_flag   ignore_repeated_source  off
#		php_value  docref_root             0
#		php_value  docref_ext              0
	</IfModule>
</Directory>
EOF
} |
sudo tee -- "$target" >/dev/null

sudo a2ensite "$project"
sudo service apache2 reload
