#!/bin/bash -ue
#
# Apache configuration generator
# Copyright (C) 2016 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>

project=conquerclub

# Constants and other globals - DO NOT CHANGE! --------------------------------

myname=${0##*/}
mydir=$(dirname "$(readlink -f "$0")")

docroot=$mydir/www
cgibin=$mydir/cgi-bin
logdir=$mydir/log

apachelog=$logdir/apache_access.log
phplog=$logdir/php_errors.log

target=/etc/apache2/sites-available/$project
apachegroup=$(
	set +u
	source /etc/apache2/envvars 2>/dev/null &&
	echo "$APACHE_RUN_GROUP" ||
	echo www-data
)


# Functions -------------------------------------------------------------------

fatal()   { [[ "$1" ]] && echo "$myname: error: $1" >&2 ; exit ${2:-1} ; }

create_log() {
	local logfile=$1
	local group=$2

	touch -- "$logfile" &&
	! [[ -d "$logfile" ]] &&
	! [[ -h "$logfile" ]] &&
	chmod 660 -- "$logfile" &&
	sudo chgrp "$group" -- "$logfile"
}

# Do stuff --------------------------------------------------------------------

sudo rm -f -- "$target"

{
cat <<EOF
# Created by $mydir/$myname

ScriptAlias /$project/cgi-bin/ "$cgibin/"
Alias /$project "$docroot"

# Access Log
# Will only work for vhosts with no CustomLog directive defined
# Log file will always be created, but will be empty
# Alternatively this could be included inside each vhost
SetEnvIf Request_URI ^/$project(/|\$) $project
CustomLog "$apachelog" combined env=$project

<Directory "$docroot">
	Options +Indexes
	IndexOptions FancyIndexing
	DirectoryIndex index.php index.html

	Order allow,deny
	allow from all

	<IfModule mod_php5.c>
		php_admin_flag   display_startup_errors  on
		php_admin_flag   display_errors          on
		php_admin_flag   html_errors             on
		php_admin_flag   track_errors            on
		php_admin_flag   log_errors              on
		php_admin_value  error_reporting         -1
		php_admin_value  error_log               "$phplog"
		php_admin_value  log_errors_max_len      0
		php_admin_value  docref_root             /doc/php-doc/html/
		php_admin_value  docref_ext              .html

		# Security suggestions
		php_admin_flag   allow_url_fopen         off
		php_admin_flag   file_uploads            off
		php_admin_flag   expose_php              off
		php_admin_value  open_basedir            "$docroot/:$cgibin/:/tmp/:/var/tmp/"

		# Already the default:
#		php_admin_flag   log_errors              on
#		php_admin_flag   report_memleaks         on
#		php_admin_flag   ignore_repeated_errors  off
#		php_admin_flag   ignore_repeated_source  off

#		php_admin_flag   allow_url_include       off
#		php_admin_flag   magic_quotes_gpc        off
#		php_admin_flag   register_globals        off
#		php_admin_flag   session.use_trans_sid   off
	</IfModule>

	<Files "phpinfo.php">
		order deny,allow
		deny from all
		allow from localhost 127.0.0.1
	</Files>
</Directory>

<Directory "$cgibin">
	Order allow,deny
	allow from all
</Directory>

# Allow access to PHP local online documentation
# Ideally this should be inside a VirtualHost block, not here
<Directory "/usr/share/doc/php-doc/html">
	Options -Indexes
	AllowOverride None
	Order allow,deny
	Allow from all
</Directory>
EOF
} |
sudo tee -- "$target"

mkdir -p -- "$logdir"
create_log "$phplog" "$apachegroup" || fatal "error creating log file $phplog"

sudo a2ensite "$project"
sudo service apache2 reload
